create_clock -name clk100 -period 10 -waveform {0 5} [get_nets {u_ddr3_fifo/clk100M}]
create_clock -name clk_x1 -period 10 -waveform {0 5} [get_pins {u_ddr3_fifo/u_ddr3/gw3_top/u_ddr_phy_top/fclkdiv/CLKOUT}]
create_clock -name mem400 -period 2.5 -waveform {0 1.25} [get_nets {u_ddr3_fifo/memory_clk}]
create_clock -name eth_clk125rx -period 8.0 -waveform {0 4.0} [get_ports {RGMII_RXCLK}]
create_clock -name eth_clk125tx -period 8.0 -waveform {0 4.0} [get_ports {RGMII_GTXCLK}]
set_clock_groups -asynchronous -group [get_clocks {clk100}] -group [get_clocks {clk_x1}]
set_clock_groups -asynchronous -group [get_clocks {clk_x1}] -group [get_clocks {mem400}]
set_clock_groups -asynchronous -group [get_clocks {clk100}] -group [get_clocks {mem400}]
