-d D:\Code\git\GoWinSDR\FPGA\Submodule\DDR_FIFO\impl\gwsynthesis\DDR_FIFO.vg
-p GW5AT-60B-PBGA484A-1
-pn GW5AT-LV60PG484AC1/I0
-cst D:\Code\git\GoWinSDR\FPGA\Submodule\DDR_FIFO\src\DDR_FIFO.cst
-cfg D:\Code\git\GoWinSDR\FPGA\Submodule\DDR_FIFO\impl\pnr\device.cfg
-sdc D:\Code\git\GoWinSDR\FPGA\Submodule\DDR_FIFO\src\gw60.sdc
-gao_crc 1111100111101110
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
-rtl_gao
