-d D:\Code\git\GoWinSDR\FPGA\Submodule\SDR_Tune\impl\gwsynthesis\SDR_Tune.vg
-p GW5AT-60B-PBGA484A-1
-pn GW5AT-LV60PG484AC1/I0
-cst D:\Code\git\GoWinSDR\FPGA\Submodule\SDR_Tune\src\SDR_Test.cst
-cfg D:\Code\git\GoWinSDR\FPGA\Submodule\SDR_Tune\impl\pnr\device.cfg
-sdc D:\Code\git\GoWinSDR\FPGA\Submodule\SDR_Tune\src\tc.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
